name: Run Tests
on:
  pull_request:
    types:
      - opened
    branches:
      - main
jobs:
  deploy:
    runs-on: ubunut-latest
    steps:
      - name: Get Code
        uses: actions/checkout@v4
      - name: Install dependencies
        run: npm ci
      - name: Run tests
        run: npm run test
